<?php
/**
 * @file
 * A description of what your module does.
 */

/**
 * Implements hook_theme() to add the template definition.
 **/

/**
 * Implements hook_theme().
 */
function js_fullwidth_theme($existing, $type, $theme, $path)
{
    $items['js-fullwidth-block'] = array(
        'variables' => array(
            'HeaderText' => NULL,
            'HeaderBgColor' => NULL,
            'HeaderTextColor' => NULL,
            '#attached' => array(
                'library' => array(
                    'js_fullwidth/colorpicker',
                ),
            ),
        ),
        'path' => $path . '/templates',
    );

    return $items;
}

function js_fullwidth_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] =
        'js_fullwidth/colorpicker';
}