<?php
/**
* @file
* A description of what your module does.
*/

/**
* Implements hook_theme() to add the template definition.
**/

/**
 * Implements hook_theme().
 */
function js_fullwidth_theme($existing, $type, $theme, $path)
{
    $items['js-fullwidth-block'] = array(
        'variables' => array(
            'HeaderText' => NULL,
            'HeaderBgColor' => NULL,
            'TextColor' => NULL
        ),
        'path' => $path . '/templates',
    );

    return $items;
}